org.gradle.jvmargs=-Xmx2560m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.enableR8.fullMode=true
android.enableResourceOptimizations=true
android.r8.gradual.support=true
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
kotlin.daemon.jvmargs=-Xmx1280m
