package com.test.tcqt.core.action

import android.app.Application
import android.os.SystemClock
import com.test.tcqt.core.dexkit.DexKitCache
import com.test.tcqt.core.dexkit.DexKitTask
import com.test.tcqt.core.env.TCQTBuild
import com.test.tcqt.core.log.Log
import com.test.tcqt.core.log.LogAndroid
import com.test.tcqt.core.reflect.new
import com.test.tcqt.generated.GeneratedActionList
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.coroutines.yield
import java.util.EnumMap
import java.util.concurrent.ConcurrentHashMap

/**
 * 一次启动中要执行的功能计划。
 *
 * [ActionRegistry.buildPlan] 只负责“决定执行什么”（进程过滤 + DexKit 缺失过滤 +
 * 按 [ActionPriority] 分组），不负责“什么时候执行”：
 * - [critical] 由调用方在 Application.onCreate 的 Before 回调中同步执行；
 * - 其余由 [StartupScheduler] 在 onCreate 返回后分批在后台线程执行。
 */
data class ActionPlan(
    val critical: List<Class<out ActionSpec>> = emptyList(),
    val early: List<Class<out ActionSpec>> = emptyList(),
    val deferred: List<Class<out ActionSpec>> = emptyList(),
    val background: List<Class<out ActionSpec>> = emptyList(),
) {
    val isEmpty: Boolean
        get() = critical.isEmpty() && early.isEmpty() && deferred.isEmpty() && background.isEmpty()
}

/**
 * 运行时 Action 注册表：实例缓存、启动计划与执行。
 *
 * 本类**不得**依赖 `ui` / `host` / `loader` —— 它是启动路径的一部分。UI 元数据在
 * `ui.settings.FeatureCatalog`，配置注册在 `core.config.SettingsRegistry`。
 */
internal object ActionRegistry {

    /** 后台分批安装时每批的 Action 数量，防止一次性吃满 CPU。 */
    private const val BATCH_SIZE = 8

    private val FIRST_ACTION = GeneratedActionList.ACTIONS // generated by KSP

    private val instanceMap = ConcurrentHashMap<Class<out ActionSpec>, ActionSpec>()

    private val failedActions = ConcurrentHashMap.newKeySet<Class<out ActionSpec>>()

    /** key -> ActionClass。仅设置 UI 需要；延迟到首次访问才构建，避免启动路径实例化全部 Action。 */
    private val keyToActionMap: Map<String, Class<out ActionSpec>> by lazy {
        val map = hashMapOf<String, Class<out ActionSpec>>()
        FIRST_ACTION.forEach { actionClass ->
            runCatching {
                val action = instanceOf(actionClass) ?: return@forEach
                if (action.key.isNotBlank()) {
                    map[action.key] = actionClass
                }
                action.settings.forEach { setting ->
                    map[setting.key] = actionClass
                }
            }
        }
        map
    }

    /** 注册清单里的全部 Action 类（KSP 生成，顺序即生成顺序）。 */
    fun allActionClasses(): List<Class<out ActionSpec>> = FIRST_ACTION.toList()

    fun instanceOf(cls: Class<out ActionSpec>): ActionSpec? {
        if (cls in failedActions) return null

        return runCatching {
            instanceMap.getOrPut(cls) { instantiate(cls) }
        }.getOrElse { e ->
            Log.e("ActionRegistry instanceOf failed", e)
            failedActions.add(cls)
            null
        }
    }

    /**
     * 取得功能的**单例**：必须取静态 `INSTANCE` 字段。
     *
     * 静默退化成 `cls.new()` 反射构造会得到**第二个实例**，Kotlin `object` 的属性
     * 初始化器在 `<clinit>` 里、不会为它执行，于是 `Feature.declaredOptions` 为空、
     * `settings` 为空 —— 设置界面里该功能的文本框/单选/多选/滑块全部消失，而 hook
     * 照常安装、开关照常显示，看起来只是"少了额外选项"。`RuntimeSettingsRegistrationTest`
     * 守着这一点。
     */
    private fun instantiate(cls: Class<out ActionSpec>): ActionSpec {
        runCatching {
            cls.getDeclaredField("INSTANCE").apply { isAccessible = true }.get(null) as? ActionSpec
        }.getOrNull()?.let { return it }

        // 非 `object`（普通 class）才走反射构造。
        return cls.new()
    }

    // ── 启动路径 ────────────────────────────────────────────────────────────

    private val BASE_PROCS = setOf(
        ActionProcess.MSF,
        ActionProcess.MAIN,
        ActionProcess.TOOL,
        ActionProcess.OPENSDK,
        ActionProcess.QZONE,
        ActionProcess.QQFAV
    )

    /**
     * 决定本进程要执行哪些功能，并按优先级分组。不执行任何 Action；
     * 执行由 [runCritical] / [runEarly] / [runDeferred] / [runBackground] 负责。
     */
    fun buildPlan(
        proc: ActionProcess,
        missingDexKitKeys: Set<String>? = null
    ): ActionPlan {
        val lists = EnumMap<ActionPriority, MutableList<Class<out ActionSpec>>>(
            ActionPriority::class.java
        )
        ActionPriority.entries.forEach { lists[it] = mutableListOf() }

        FIRST_ACTION.forEach { actionClass ->
            // DexKit 依赖检查：缺失 key 的 DexKitTask 本轮跳过（等后台查找 + 重启后再装）
            if (DexKitTask::class.java.isAssignableFrom(actionClass)) {
                val dexKitTask = runCatching {
                    instanceOf(actionClass) as? DexKitTask
                }.getOrNull()
                if (dexKitTask != null) {
                    val taskKeys = dexKitTask.getCacheKeys()
                    val shouldSkip = taskKeys.any { key ->
                        (missingDexKitKeys != null && key in missingDexKitKeys) ||
                                DexKitCache.cacheMap[key]?.isEmpty() == true
                    }
                    if (shouldSkip) {
                        return@forEach
                    }
                }
            }

            val action = instanceOf(actionClass) ?: run {
                if (TCQTBuild.DEBUG) {
                    Log.e("instanceOf [${actionClass.simpleName}] failed")
                }
                return@forEach
            }

            val shouldRun =
                ActionProcess.ALL in action.processes ||
                        proc in action.processes ||
                        (ActionProcess.OTHER in action.processes && proc !in BASE_PROCS)
            if (!shouldRun) return@forEach

            lists.getValue(action.priority).add(actionClass)
        }

        return ActionPlan(
            critical = lists[ActionPriority.CRITICAL] ?: emptyList(),
            early = lists[ActionPriority.EARLY] ?: emptyList(),
            deferred = lists[ActionPriority.DEFERRED] ?: emptyList(),
            background = lists[ActionPriority.BACKGROUND] ?: emptyList(),
        )
    }

    /** 同步执行 [ActionPlan.critical]，必须保持在主线程且数量尽量少。 */
    fun runCritical(app: Application, proc: ActionProcess, plan: ActionPlan) {
        runAll(app, proc, plan.critical, "Critical")
    }

    /** onCreate 返回后立刻在后台线程执行 [ActionPlan.early]。 */
    fun runEarly(app: Application, proc: ActionProcess, plan: ActionPlan) {
        runAll(app, proc, plan.early, "Early")
    }

    /** 后台分批执行 [ActionPlan.deferred]。 */
    suspend fun runDeferred(app: Application, proc: ActionProcess, plan: ActionPlan) {
        runBatched(app, proc, plan.deferred, "Deferred")
    }

    /** 后台分批执行 [ActionPlan.background]。 */
    suspend fun runBackground(app: Application, proc: ActionProcess, plan: ActionPlan) {
        runBatched(app, proc, plan.background, "Background")
    }

    private fun runAll(
        app: Application,
        proc: ActionProcess,
        classes: List<Class<out ActionSpec>>,
        tag: String
    ) {
        if (classes.isEmpty()) return
        val phaseStart = SystemClock.elapsedRealtime()
        classes.forEach { executeOne(it, app, proc) }
        val phaseCost = SystemClock.elapsedRealtime() - phaseStart
        LogAndroid.d("[ActionPerf] [$tag] ${classes.size} 个功能共耗时 ${phaseCost}ms")
    }

    private suspend fun runBatched(
        app: Application,
        proc: ActionProcess,
        classes: List<Class<out ActionSpec>>,
        tag: String
    ) {
        if (classes.isEmpty()) return
        val phaseStart = SystemClock.elapsedRealtime()
        val batches = classes.chunked(BATCH_SIZE)
        batches.forEachIndexed { index, batch ->
            withContext(Dispatchers.Default) {
                batch.forEach { executeOne(it, app, proc) }
            }
            // 让出调度，避免一次性吃满后台 CPU / 与宿主后台任务争抢
            if (index != batches.lastIndex) {
                yield()
            }
        }
        val phaseCost = SystemClock.elapsedRealtime() - phaseStart
        LogAndroid.d("[ActionPerf] [$tag] ${classes.size} 个功能共耗时 ${phaseCost}ms")
    }

    private fun executeOne(
        actionClass: Class<out ActionSpec>,
        app: Application,
        proc: ActionProcess
    ) {
        val start = SystemClock.elapsedRealtime()
        runCatching {
            val action = instanceOf(actionClass) ?: return
            action(app, proc)
        }.onFailure { e ->
            Log.e("Action [${actionClass.simpleName}] 执行异常", e)
        }
        val cost = SystemClock.elapsedRealtime() - start
        if (TCQTBuild.DEBUG || cost >= 30) {
            LogAndroid.d(
                "[ActionPerf] ${actionClass.simpleName}: ${cost}ms [${Thread.currentThread().name}]"
            )
        }
    }

    // ── 日志辅助 ────────────────────────────────────────────────────────────

    /** 解析用于日志/异常报告的功能名：优先 name，其次 key，最后类名。 */
    fun resolve(action: ActionSpec): String {
        if (action.name.isNotBlank()) {
            return action.name
        }
        if (action.key.isNotBlank()) {
            return action.key
        }
        return action::class.simpleName ?: "Unknown"
    }

    /** 按 key 取 Action 实例（key 命中功能开关或任一配置项）。 */
    fun getActionByKey(key: String): ActionSpec? {
        val actionClass = keyToActionMap[key] ?: return null
        return instanceOf(actionClass)
    }
}
